movie_list = [{"url": ["http://www.imdb.com/title/tt2015381/"], "rating": [" 8.7 "], "year": ["2014"], "genre": ["Action", "Adventure", "Sci-Fi"], "title": ["Guardians of the Galaxy"]},
{"url": ["http://www.imdb.com/title/tt1800241/"], "rating": [" 7.4 "], "year": ["2013"], "genre": ["Crime", "Drama"], "title": ["American Hustle"]},
{"url": ["http://www.imdb.com/title/tt3460252/"], "rating": [], "year": ["2015"], "genre": ["Western"], "title": ["The Hateful Eight"]},
{"url": ["http://www.imdb.com/title/tt1981115/"], "rating": [" 7.2 "], "year": ["2013"], "genre": ["Action", "Adventure", "Fantasy"], "title": ["Thor: The Dark World"]},
{"url": ["http://www.imdb.com/title/tt1937390/"], "rating": [" 7.2 "], "year": ["2013"], "genre": ["Drama"], "title": ["Nymphomaniac: Vol. I"]},
{"url": ["http://www.imdb.com/title/tt2820852/"], "rating": [], "year": ["2015"], "genre": ["Action", "Crime", "Thriller"], "title": ["Fast & Furious 7"]},
{"url": ["http://www.imdb.com/title/tt0770828/"], "rating": [" 7.3 "], "year": ["2013"], "genre": ["Action", "Adventure", "Fantasy"], "title": ["Man of Steel"]},
{"url": ["http://www.imdb.com/title/tt0068646/"], "rating": [" 9.2 "], "year": ["1972"], "genre": ["Crime", "Drama"], "title": ["The Godfather"]},
{"url": ["http://www.imdb.com/title/tt2183034/"], "rating": [" 5.9 "], "year": ["2014"], "genre": ["Adventure", "Family", "Sci-Fi"], "title": ["Earth to Echo"]},
{"url": ["http://www.imdb.com/title/tt2357291/"], "rating": [" 6.5 "], "year": ["2014"], "genre": ["Animation", "Adventure", "Comedy"], "title": ["Rio 2"]},
{"url": ["http://www.imdb.com/title/tt2234155/"], "rating": [" 6.4 "], "year": ["2013"], "genre": ["Comedy"], "title": ["The Internship"]},
{"url": ["http://www.imdb.com/title/tt2377322/"], "rating": [" 6.5 "], "year": ["2014"], "genre": ["Crime", "Horror", "Thriller"], "title": ["Deliver Us from Evil"]},
{"url": ["http://www.imdb.com/title/tt1486834/"], "rating": [" 7.1 "], "year": ["2013"], "genre": ["Comedy", "Drama", "Romance"], "title": ["What If"]},
{"url": ["http://www.imdb.com/title/tt0111161/"], "rating": [" 9.3 "], "year": ["1994"], "genre": ["Crime", "Drama"], "title": ["The Shawshank Redemption"]},
{"url": ["http://www.imdb.com/title/tt0401792/"], "rating": [" 8.2 "], "year": ["2005"], "genre": ["Crime", "Thriller"], "title": ["Sin City"]},
{"url": ["http://www.imdb.com/title/tt0458339/"], "rating": [" 6.8 "], "year": ["2011"], "genre": ["Action", "Adventure", "Sci-Fi"], "title": ["Captain America: The First Avenger"]},
{"url": ["http://www.imdb.com/title/tt0831387/"], "rating": [" 7.1 "], "year": ["2014"], "genre": ["Action", "Sci-Fi", "Thriller"], "title": ["Godzilla"]},
{"url": ["http://www.imdb.com/title/tt1392170/"], "rating": [" 7.3 "], "year": ["2012"], "genre": ["Adventure", "Sci-Fi"], "title": ["The Hunger Games"]},
{"url": ["http://www.imdb.com/title/tt2582802/"], "rating": [" 7.5 "], "year": ["2014"], "genre": ["Drama"], "title": ["Whiplash"]},
{"url": ["http://www.imdb.com/title/tt0468569/"], "rating": [" 9.0 "], "year": ["2008"], "genre": ["Action", "Drama", "Thriller"], "title": ["The Dark Knight"]},
{"url": ["http://www.imdb.com/title/tt0133152/"], "rating": [" 5.7 "], "year": ["2001"], "genre": ["Action", "Adventure", "Sci-Fi"], "title": ["Planet of the Apes"]},
{"url": ["http://www.imdb.com/title/tt1924435/"], "rating": [], "year": ["2014"], "genre": ["Action", "Comedy"], "title": ["Let's Be Cops"]},
{"url": ["http://www.imdb.com/title/tt2488496/"], "rating": [], "year": ["2015"], "genre": ["Action", "Adventure", "Fantasy"], "title": ["Star Wars: Episode VII"]},
{"url": ["http://www.imdb.com/title/tt1345836/"], "rating": [" 8.6 "], "year": ["2012"], "genre": ["Action", "Thriller"], "title": ["The Dark Knight Rises"]},
{"url": ["http://www.imdb.com/title/tt2024469/"], "rating": [" 7.1 "], "year": ["2014"], "genre": ["Action", "Mystery", "Thriller"], "title": ["Non-Stop"]},
{"url": ["http://www.imdb.com/title/tt2004420/"], "rating": [" 6.9 "], "year": ["2014"], "genre": ["Comedy"], "title": ["Neighbors"]},
{"url": ["http://www.imdb.com/title/tt0369610/"], "rating": [], "year": ["2015"], "genre": ["Action", "Adventure", "Sci-Fi"], "title": ["Jurassic World"]},
{"url": ["http://www.imdb.com/title/tt1981677/"], "rating": [" 7.3 "], "year": ["2012"], "genre": ["Comedy", "Music", "Romance"], "title": ["Pitch Perfect"]},
{"url": ["http://www.imdb.com/title/tt2234003/"], "rating": [" 7.6 "], "year": ["2014"], "genre": ["Drama"], "title": ["Calvary"]},
{"url": ["http://www.imdb.com/title/tt0169547/"], "rating": [" 8.5 "], "year": ["1999"], "genre": ["Drama"], "title": ["American Beauty"]},
{"url": ["http://www.imdb.com/title/tt1091191/"], "rating": [" 7.7 "], "year": ["2013"], "genre": ["Action", "Biography", "Drama"], "title": ["Lone Survivor"]},
{"url": ["http://www.imdb.com/title/tt2562232/"], "rating": [], "year": ["2014"], "genre": ["Comedy", "Drama"], "title": ["Birdman"]},
{"url": ["http://www.imdb.com/title/tt1714206/"], "rating": [" 7.3 "], "year": ["2013"], "genre": ["Comedy", "Drama", "Romance"], "title": ["The Spectacular Now"]},
{"url": ["http://www.imdb.com/title/tt1661199/"], "rating": [], "year": ["2015"], "genre": ["Adventure", "Drama", "Family"], "title": ["Cinderella"]},
{"url": ["http://www.imdb.com/title/tt0829482/"], "rating": [" 7.7 "], "year": ["2007"], "genre": ["Comedy"], "title": ["Superbad"]},
{"url": ["http://www.imdb.com/title/tt1980209/"], "rating": [" 6.5 "], "year": ["2013"], "genre": ["Action", "Comedy", "Crime"], "title": ["Pain & Gain"]},
{"url": ["http://www.imdb.com/title/tt0332280/"], "rating": [" 8.0 "], "year": ["2004"], "genre": ["Drama", "Romance"], "title": ["The Notebook"]},
{"url": ["http://www.imdb.com/title/tt1300854/"], "rating": [" 7.4 "], "year": ["2013"], "genre": ["Action", "Adventure", "Sci-Fi"], "title": ["Iron Man 3"]},
{"url": ["http://www.imdb.com/title/tt0800369/"], "rating": [" 7.0 "], "year": ["2011"], "genre": ["Action", "Adventure", "Fantasy"], "title": ["Thor"]},
{"url": ["http://www.imdb.com/title/tt2848292/"], "rating": [], "year": ["2015"], "genre": ["Comedy", "Music"], "title": ["Pitch Perfect 2"]},
{"url": ["http://www.imdb.com/title/tt2172934/"], "rating": [" 6.2 "], "year": ["2014"], "genre": ["Action", "Drama", "Thriller"], "title": ["3 Days to Kill"]},
{"url": ["http://www.imdb.com/title/tt0359950/"], "rating": [" 7.4 "], "year": ["2013"], "genre": ["Adventure", "Comedy", "Drama"], "title": ["The Secret Life of Walter Mitty"]},
{"url": ["http://www.imdb.com/title/tt0416449/"], "rating": [" 7.8 "], "year": ["2006"], "genre": ["Action", "Fantasy", "War"], "title": ["300"]},
{"url": ["http://www.imdb.com/title/tt1327773/"], "rating": [" 7.1 "], "year": ["2013"], "genre": ["Biography", "Drama"], "title": ["Lee Daniels' The Butler"]},
{"url": ["http://www.imdb.com/title/tt0418279/"], "rating": [" 7.2 "], "year": ["2007"], "genre": ["Action", "Adventure", "Sci-Fi"], "title": ["Transformers"]},
{"url": ["http://www.imdb.com/title/tt1853614/"], "rating": [" 7.3 "], "year": ["2011"], "genre": ["Animation", "Drama", "Family"], "title": ["A Letter to Momo"]},
{"url": ["http://www.imdb.com/title/tt0120783/"], "rating": [" 6.3 "], "year": ["1998"], "genre": ["Adventure", "Comedy", "Drama"], "title": ["The Parent Trap"]},
{"url": ["http://www.imdb.com/title/tt2101441/"], "rating": [" 5.3 "], "year": ["2012"], "genre": ["Crime", "Drama"], "title": ["Spring Breakers"]},
{"url": ["http://www.imdb.com/title/tt1340138/"], "rating": [], "year": ["2015"], "genre": ["Action", "Adventure", "Sci-Fi"], "title": ["Terminator: Genisys"]},
{"url": ["http://www.imdb.com/title/tt2191701/"], "rating": [" 5.4 "], "year": ["2013"], "genre": ["Comedy"], "title": ["Grown Ups 2"]},
{"url": ["http://www.imdb.com/title/tt0482571/"], "rating": [" 8.5 "], "year": ["2006"], "genre": ["Drama", "Mystery", "Thriller"], "title": ["The Prestige"]},
{"url": ["http://www.imdb.com/title/tt0102926/"], "rating": [" 8.6 "], "year": ["1991"], "genre": ["Crime", "Drama", "Thriller"], "title": ["The Silence of the Lambs"]},
{"url": ["http://www.imdb.com/title/tt2223990/"], "rating": [" 6.9 "], "year": ["2014"], "genre": ["Drama", "Sport"], "title": ["Draft Day"]},
{"url": ["http://www.imdb.com/title/tt2250912/"], "rating": [], "year": ["2018"], "genre": ["Action", "Adventure", "Fantasy"], "title": ["The Amazing Spider-Man 3"]},
{"url": ["http://www.imdb.com/title/tt0145487/"], "rating": [" 7.3 "], "year": ["2002"], "genre": ["Action", "Adventure"], "title": ["Spider-Man"]},
{"url": ["http://www.imdb.com/title/tt0816711/"], "rating": [" 7.1 "], "year": ["2013"], "genre": ["Action", "Adventure", "Horror"], "title": ["World War Z"]},
{"url": ["http://www.imdb.com/title/tt1074638/"], "rating": [" 7.8 "], "year": ["2012"], "genre": ["Action", "Thriller"], "title": ["Skyfall"]},
{"url": ["http://www.imdb.com/title/tt0405422/"], "rating": [" 7.2 "], "year": ["2005"], "genre": ["Comedy", "Romance"], "title": ["The 40-Year-Old Virgin"]},
{"url": ["http://www.imdb.com/title/tt2334879/"], "rating": [" 6.4 "], "year": ["2013"], "genre": ["Action", "Drama", "Thriller"], "title": ["White House Down"]},
{"url": ["http://www.imdb.com/title/tt0081505/"], "rating": [" 8.5 "], "year": ["1980"], "genre": ["Horror"], "title": ["The Shining"]},
{"url": ["http://www.imdb.com/title/tt2679042/"], "rating": [], "year": ["2015"], "genre": ["Action", "Crime", "Thriller"], "title": ["Agent 47"]},
{"url": ["http://www.imdb.com/title/tt0118715/"], "rating": [" 8.2 "], "year": ["1998"], "genre": ["Comedy", "Crime"], "title": ["The Big Lebowski"]},
{"url": ["http://www.imdb.com/title/tt1446714/"], "rating": [" 7.1 "], "year": ["2012"], "genre": ["Adventure", "Mystery", "Sci-Fi"], "title": ["Prometheus"]},
{"url": ["http://www.imdb.com/title/tt2140373/"], "rating": [" 7.6 "], "year": ["2013"], "genre": ["Biography", "Comedy", "Drama"], "title": ["Saving Mr. Banks"]},
{"url": ["http://www.imdb.com/title/tt0246578/"], "rating": [" 8.1 "], "year": ["2001"], "genre": ["Drama", "Mystery", "Sci-Fi"], "title": ["Donnie Darko"]},
{"url": ["http://www.imdb.com/title/tt0099685/"], "rating": [" 8.7 "], "year": ["1990"], "genre": ["Biography", "Crime", "Drama"], "title": ["Goodfellas"]},
{"url": ["http://www.imdb.com/title/tt1935179/"], "rating": [" 7.5 "], "year": ["2012"], "genre": ["Drama"], "title": ["Mud"]},
{"url": ["http://www.imdb.com/title/tt0816442/"], "rating": [" 7.6 "], "year": ["2013"], "genre": ["Drama", "War"], "title": ["The Book Thief"]},
{"url": ["http://www.imdb.com/title/tt0311289/"], "rating": [" 7.1 "], "year": ["2003"], "genre": ["Adventure", "Comedy", "Drama"], "title": ["Holes"]},
{"url": ["http://www.imdb.com/title/tt1418377/"], "rating": [" 5.2 "], "year": ["2014"], "genre": ["Action", "Fantasy", "Sci-Fi"], "title": ["I, Frankenstein"]},
{"url": ["http://www.imdb.com/title/tt0822854/"], "rating": [" 7.2 "], "year": ["2007"], "genre": ["Action", "Crime", "Drama"], "title": ["Shooter"]},
{"url": ["http://www.imdb.com/title/tt1742044/"], "rating": [" 7.3 "], "year": ["2014"], "genre": ["Biography", "Drama", "Music"], "title": ["Jersey Boys"]},
{"url": ["http://www.imdb.com/title/tt2463288/"], "rating": [" 6.1 "], "year": ["2014"], "genre": ["Comedy"], "title": ["Walk of Shame"]},
{"url": ["http://www.imdb.com/title/tt0314331/"], "rating": [" 7.7 "], "year": ["2003"], "genre": ["Comedy", "Drama", "Romance"], "title": ["Love Actually"]},
{"url": ["http://www.imdb.com/title/tt1371111/"], "rating": [" 7.6 "], "year": ["2012"], "genre": ["Drama", "Sci-Fi"], "title": ["Cloud Atlas"]},
{"url": ["http://www.imdb.com/title/tt1707386/"], "rating": [" 7.7 "], "year": ["2012"], "genre": ["Drama", "Musical", "Romance"], "title": ["Les Mis\u00e9rables"]},
{"url": ["http://www.imdb.com/title/tt0078748/"], "rating": [" 8.5 "], "year": ["1979"], "genre": ["Horror", "Sci-Fi"], "title": ["Alien"]},
{"url": ["http://www.imdb.com/title/tt1179031/"], "rating": [" 7.3 "], "year": ["2014"], "genre": ["Crime", "Thriller"], "title": ["Cold in July"]},
{"url": ["http://www.imdb.com/title/tt0325980/"], "rating": [" 8.1 "], "year": ["2003"], "genre": ["Action", "Adventure", "Fantasy"], "title": ["Pirates of the Caribbean: The Curse of the Black Pearl"]},
{"url": ["https://pro-labs.imdb.com/title/tt2250912?d=tt_indev"], "rating": [], "year": [], "genre": [], "title": []},
{"url": ["http://www.imdb.com/title/tt2528814/"], "rating": [" 4.8 "], "year": ["2014"], "genre": ["Drama"], "title": ["God's Not Dead"]},
{"url": ["http://www.imdb.com/title/tt0274812/"], "rating": [" 7.1 "], "year": ["2002"], "genre": ["Comedy", "Drama", "Romance"], "title": ["Secretary"]},
{"url": ["http://www.imdb.com/title/tt1535109/"], "rating": [" 7.9 "], "year": ["2013"], "genre": ["Biography", "Drama", "Thriller"], "title": ["Captain Phillips"]},
{"url": ["http://www.imdb.com/title/tt0114814/"], "rating": [" 8.7 "], "year": ["1995"], "genre": ["Crime", "Drama", "Thriller"], "title": ["The Usual Suspects"]},
{"url": ["http://www.imdb.com/title/tt1686821/"], "rating": [" 5.7 "], "year": ["2014"], "genre": ["Action", "Comedy", "Fantasy"], "title": ["Vampire Academy"]},
{"url": ["http://www.imdb.com/title/tt0330373/"], "rating": [" 7.6 "], "year": ["2005"], "genre": ["Adventure", "Family", "Fantasy"], "title": ["Harry Potter and the Goblet of Fire"]},
{"url": ["http://www.imdb.com/title/tt0071562/"], "rating": [" 9.1 "], "year": ["1974"], "genre": ["Crime", "Drama"], "title": ["The Godfather: Part II"]},
{"url": ["http://www.imdb.com/title/tt2527186/"], "rating": [" 5.3 "], "year": ["2013"], "genre": ["Comedy", "Horror", "Thriller"], "title": ["All Cheerleaders Die"]},
{"url": ["http://www.imdb.com/title/tt0265208/"], "rating": [" 6.8 "], "year": ["2004"], "genre": ["Comedy", "Drama", "Romance"], "title": ["The Girl Next Door"]},
{"url": ["http://www.imdb.com/title/tt0163651/"], "rating": [" 7.0 "], "year": ["1999"], "genre": ["Comedy", "Romance"], "title": ["American Pie"]},
{"url": ["http://www.imdb.com/title/tt0458525/"], "rating": [" 6.7 "], "year": ["2009"], "genre": ["Action", "Adventure", "Sci-Fi"], "title": ["X-Men Origins: Wolverine"]},
{"url": ["http://www.imdb.com/title/tt1276104/"], "rating": [" 7.5 "], "year": ["2012"], "genre": ["Action", "Crime", "Sci-Fi"], "title": ["Looper"]},
{"url": ["http://www.imdb.com/title/tt1411250/"], "rating": [" 6.4 "], "year": ["2013"], "genre": ["Action", "Sci-Fi", "Thriller"], "title": ["Riddick"]},
{"url": ["http://www.imdb.com/title/tt1291584/"], "rating": [" 8.3 "], "year": ["2011"], "genre": ["Drama", "Sport"], "title": ["Warrior"]},
{"url": ["http://www.imdb.com/title/tt1817273/"], "rating": [" 7.4 "], "year": ["2012"], "genre": ["Crime", "Drama"], "title": ["The Place Beyond the Pines"]},
{"url": ["http://www.imdb.com/title/tt1790885/"], "rating": [" 7.4 "], "year": ["2012"], "genre": ["Drama", "History", "Thriller"], "title": ["Zero Dark Thirty"]},
{"url": ["http://www.imdb.com/title/tt0088763/"], "rating": [" 8.5 "], "year": ["1985"], "genre": ["Adventure", "Comedy", "Sci-Fi"], "title": ["Back to the Future"]},
{"url": ["http://www.imdb.com/title/tt0093779/"], "rating": [" 8.2 "], "year": ["1987"], "genre": ["Adventure", "Comedy", "Family"], "title": ["The Princess Bride"]},
{"url": ["http://www.imdb.com/title/tt1758830/"], "rating": [" 6.2 "], "year": ["2012"], "genre": ["Comedy"], "title": ["This Is 40"]},
{"url": ["http://www.imdb.com/title/tt2278871/"], "rating": [" 7.9 "], "year": ["2013"], "genre": ["Drama", "Romance"], "title": ["Blue Is the Warmest Color"]},
{"url": ["http://www.imdb.com/title/tt1259521/"], "rating": [" 7.1 "], "year": ["2012"], "genre": ["Horror", "Mystery", "Thriller"], "title": ["The Cabin in the Woods"]},
{"url": ["http://www.imdb.com/title/tt0409459/"], "rating": [" 7.6 "], "year": ["2009"], "genre": ["Action", "Mystery", "Sci-Fi"], "title": ["Watchmen"]},
{"url": ["http://www.imdb.com/title/tt0110413/"], "rating": [" 8.6 "], "year": ["1994"], "genre": ["Crime", "Drama", "Thriller"], "title": ["L\u00e9on: The Professional"]},
{"url": ["http://www.imdb.com/title/tt1617661/"], "rating": [], "year": ["2015"], "genre": ["Action", "Adventure", "Sci-Fi"], "title": ["Jupiter Ascending"]},
{"url": ["http://www.imdb.com/title/tt2096672/"], "rating": [], "year": ["2014"], "genre": ["Comedy"], "title": ["Dumb and Dumber To"]},
{"url": ["http://www.imdb.com/title/tt2870612/"], "rating": [], "year": ["2014"], "genre": ["Horror", "Thriller"], "title": ["As Above, So Below"]},
{"url": ["http://www.imdb.com/title/tt0133093/"], "rating": [" 8.7 "], "year": ["1999"], "genre": ["Action", "Sci-Fi"], "title": ["The Matrix"]},
{"url": ["http://www.imdb.com/title/tt1130884/"], "rating": [" 8.1 "], "year": ["2010"], "genre": ["Mystery", "Thriller"], "title": ["Shutter Island"]},
{"url": ["http://www.imdb.com/title/tt1333125/"], "rating": [" 4.4 "], "year": ["2013"], "genre": ["Comedy"], "title": ["Movie 43"]},
{"url": ["http://www.imdb.com/title/tt2382396/"], "rating": [" 7.0 "], "year": ["2013"], "genre": ["Drama"], "title": ["Joe"]},
{"url": ["http://www.imdb.com/title/tt1430612/"], "rating": [" 5.8 "], "year": ["2014"], "genre": ["Action", "Crime", "Drama"], "title": ["Brick Mansions"]},
{"url": ["http://www.imdb.com/title/tt1212450/"], "rating": [" 7.3 "], "year": ["2012"], "genre": ["Crime", "Drama"], "title": ["Lawless"]},
{"url": ["http://www.imdb.com/title/tt0455944/"], "rating": [], "year": ["2014"], "genre": ["Action", "Crime", "Thriller"], "title": ["The Equalizer"]},
{"url": ["http://www.imdb.com/title/tt0089218/"], "rating": [" 7.8 "], "year": ["1985"], "genre": ["Adventure", "Comedy", "Family"], "title": ["The Goonies"]},
{"url": ["http://www.imdb.com/title/tt0407887/"], "rating": [" 8.5 "], "year": ["2006"], "genre": ["Crime", "Drama", "Thriller"], "title": ["The Departed"]},
{"url": ["http://www.imdb.com/title/tt1250777/"], "rating": [" 7.8 "], "year": ["2010"], "genre": ["Action", "Comedy"], "title": ["Kick-Ass"]},
{"url": ["http://www.imdb.com/title/tt2359024/"], "rating": [" 7.1 "], "year": ["2013"], "genre": ["Thriller"], "title": ["Blue Ruin"]},
{"url": ["http://www.imdb.com/title/tt0120903/"], "rating": [" 7.4 "], "year": ["2000"], "genre": ["Action", "Adventure", "Sci-Fi"], "title": ["X-Men"]},
{"url": ["http://www.imdb.com/title/tt0144084/"], "rating": [" 7.6 "], "year": ["2000"], "genre": ["Crime", "Drama"], "title": ["American Psycho"]},
{"url": ["http://www.imdb.com/title/tt1068242/"], "rating": [" 5.8 "], "year": ["2011"], "genre": ["Comedy", "Drama", "Music"], "title": ["Footloose"]},
{"url": ["http://www.imdb.com/title/tt1430132/"], "rating": [" 6.8 "], "year": ["2013"], "genre": ["Action", "Adventure", "Sci-Fi"], "title": ["The Wolverine"]},
{"url": ["http://www.imdb.com/title/tt1399103/"], "rating": [" 6.4 "], "year": ["2011"], "genre": ["Action", "Adventure", "Sci-Fi"], "title": ["Transformers: Dark of the Moon"]},
{"url": ["http://www.imdb.com/title/tt1100089/"], "rating": [" 8.0 "], "year": ["2014"], "genre": ["Drama"], "title": ["Foxcatcher"]},
{"url": ["http://www.imdb.com/title/tt2170299/"], "rating": [" 6.7 "], "year": ["2013"], "genre": ["Comedy"], "title": ["Bad Words"]},
{"url": ["http://www.imdb.com/title/tt0087538/"], "rating": [" 7.2 "], "year": ["1984"], "genre": ["Action", "Drama", "Family"], "title": ["The Karate Kid"]},
{"url": ["http://www.imdb.com/title/tt0109830/"], "rating": [" 8.8 "], "year": ["1994"], "genre": ["Drama", "Romance"], "title": ["Forrest Gump"]},
{"url": ["http://www.imdb.com/title/tt0864835/"], "rating": [" 7.0 "], "year": ["2014"], "genre": ["Animation", "Adventure", "Comedy"], "title": ["Mr. Peabody & Sherman"]},
{"url": ["http://www.imdb.com/title/tt0790736/"], "rating": [" 5.6 "], "year": ["2013"], "genre": ["Action", "Comedy", "Crime"], "title": ["R.I.P.D."]},
{"url": ["http://www.imdb.com/title/tt0892769/"], "rating": [" 8.2 "], "year": ["2010"], "genre": ["Animation", "Adventure", "Family"], "title": ["How to Train Your Dragon"]},
{"url": ["http://www.imdb.com/title/tt0116629/"], "rating": [" 6.9 "], "year": ["1996"], "genre": ["Action", "Adventure", "Sci-Fi"], "title": ["Independence Day"]},
{"url": ["http://www.imdb.com/title/tt2403021/"], "rating": [" 6.1 "], "year": ["2013"], "genre": ["Adventure", "Horror"], "title": ["The Green Inferno"]},
{"url": ["http://www.imdb.com/title/tt1099212/"], "rating": [" 5.2 "], "year": ["2008"], "genre": ["Drama", "Fantasy", "Romance"], "title": ["Twilight"]},
{"url": ["http://www.imdb.com/title/tt1045658/"], "rating": [" 7.9 "], "year": ["2012"], "genre": ["Comedy", "Drama", "Romance"], "title": ["Silver Linings Playbook"]},
{"url": ["http://www.imdb.com/title/tt1483013/"], "rating": [" 7.0 "], "year": ["2013"], "genre": ["Action", "Adventure", "Mystery"], "title": ["Oblivion"]},
{"url": ["http://www.imdb.com/title/tt3532608/"], "rating": [" 6.2 "], "year": ["2014"], "genre": ["Comedy"], "title": ["The Fluffy Movie: Unity Through Laughter"]},
{"url": ["http://www.imdb.com/title/tt2235108/"], "rating": [" 4.2 "], "year": ["2014"], "genre": ["Comedy", "Drama"], "title": ["Dear White People"]},
{"url": ["http://www.imdb.com/title/tt2177771/"], "rating": [" 6.1 "], "year": ["2014"], "genre": ["Biography", "Drama", "War"], "title": ["The Monuments Men"]},
{"url": ["http://www.imdb.com/title/tt2059171/"], "rating": [" 6.2 "], "year": ["2014"], "genre": ["Horror", "Thriller"], "title": ["13 Sins"]},
{"url": ["http://www.imdb.com/title/tt1731141/"], "rating": [" 6.8 "], "year": ["2013"], "genre": ["Action", "Sci-Fi"], "title": ["Ender's Game"]},
{"url": ["http://www.imdb.com/title/tt0092005/"], "rating": [" 8.1 "], "year": ["1986"], "genre": ["Adventure", "Drama"], "title": ["Stand by Me"]},
{"url": ["http://www.imdb.com/title/tt0499549/"], "rating": [" 7.9 "], "year": ["2009"], "genre": ["Action", "Adventure", "Fantasy"], "title": ["Avatar"]},
{"url": ["http://www.imdb.com/title/tt1570728/"], "rating": [" 7.5 "], "year": ["2011"], "genre": ["Comedy", "Drama", "Romance"], "title": ["Crazy, Stupid, Love."]},
{"url": ["http://www.imdb.com/title/tt0167260/"], "rating": [" 8.9 "], "year": ["2003"], "genre": ["Action", "Adventure", "Fantasy"], "title": ["The Lord of the Rings: The Return of the King"]},
{"url": ["http://www.imdb.com/title/tt2193215/"], "rating": [" 5.4 "], "year": ["2013"], "genre": ["Crime", "Drama", "Thriller"], "title": ["The Counselor"]},
{"url": ["http://www.imdb.com/title/tt2802144/"], "rating": [], "year": ["2015"], "genre": ["Action", "Adventure", "Comedy"], "title": ["Kingsman: The Secret Service"]},
{"url": ["http://www.imdb.com/title/tt0076759/"], "rating": [" 8.7 "], "year": ["1977"], "genre": ["Action", "Adventure", "Fantasy"], "title": ["Star Wars: Episode IV - A New Hope"]},
{"url": ["http://www.imdb.com/title/tt2245084/"], "rating": [], "year": ["2014"], "genre": ["Animation", "Action", "Comedy"], "title": ["Big Hero 6"]},
{"url": ["http://www.imdb.com/title/tt1979320/"], "rating": [" 8.2 "], "year": ["2013"], "genre": ["Action", "Biography", "Drama"], "title": ["Rush"]},
{"url": ["http://www.imdb.com/title/tt0434409/"], "rating": [" 8.2 "], "year": ["2005"], "genre": ["Action", "Drama", "Sci-Fi"], "title": ["V for Vendetta"]},
{"url": ["http://www.imdb.com/title/tt3322940/"], "rating": [], "year": ["2014"], "genre": ["Horror"], "title": ["Annabelle"]},
{"url": ["http://www.imdb.com/title/tt0172495/"], "rating": [" 8.5 "], "year": ["2000"], "genre": ["Action", "Drama"], "title": ["Gladiator"]},
{"url": ["http://www.imdb.com/title/tt2318092/"], "rating": [" 6.3 "], "year": ["2014"], "genre": ["Drama", "Romance"], "title": ["Endless Love"]},
{"url": ["http://www.imdb.com/title/tt1915581/"], "rating": [" 6.1 "], "year": ["2012"], "genre": ["Comedy", "Drama"], "title": ["Magic Mike"]},
{"url": ["http://www.imdb.com/title/tt2229499/"], "rating": [" 6.7 "], "year": ["2013"], "genre": ["Comedy", "Drama", "Romance"], "title": ["Don Jon"]},
{"url": ["http://www.imdb.com/title/tt1320253/"], "rating": [" 6.5 "], "year": ["2010"], "genre": ["Action", "Adventure", "Thriller"], "title": ["The Expendables"]},
{"url": ["http://www.imdb.com/title/tt1854564/"], "rating": [" 5.9 "], "year": ["2013"], "genre": ["Adventure", "Family", "Fantasy"], "title": ["Percy Jackson: Sea of Monsters"]},
{"url": ["http://www.imdb.com/title/tt0120338/"], "rating": [" 7.7 "], "year": ["1997"], "genre": ["Drama", "Romance"], "title": ["Titanic"]},
{"url": ["http://www.imdb.com/title/tt1205537/"], "rating": [" 6.2 "], "year": ["2014"], "genre": ["Action", "Mystery", "Thriller"], "title": ["Jack Ryan: Shadow Recruit"]},
{"url": ["http://www.imdb.com/title/tt1502712/"], "rating": [], "year": ["2015"], "genre": ["Action", "Fantasy", "Sci-Fi"], "title": ["The Fantastic Four"]},
{"url": ["http://www.imdb.com/title/tt2908446/"], "rating": [], "year": ["2015"], "genre": ["Adventure", "Romance", "Sci-Fi"], "title": ["Insurgent"]},
{"url": ["http://www.imdb.com/title/tt0790636/"], "rating": [" 8.0 "], "year": ["2013"], "genre": ["Biography", "Drama"], "title": ["Dallas Buyers Club"]},
{"url": ["http://www.imdb.com/title/tt1659337/"], "rating": [" 8.1 "], "year": ["2012"], "genre": ["Drama", "Romance"], "title": ["The Perks of Being a Wallflower"]},
{"url": ["http://www.imdb.com/title/tt1921064/"], "rating": [" 5.7 "], "year": ["2014"], "genre": ["Action", "Adventure", "Drama"], "title": ["Pompeii"]},
{"url": ["http://www.imdb.com/title/tt2194499/"], "rating": [" 7.8 "], "year": ["2013"], "genre": ["Drama", "Fantasy", "Romance"], "title": ["About Time"]},
{"url": ["http://www.imdb.com/title/tt0089530/"], "rating": [" 6.2 "], "year": ["1985"], "genre": ["Action", "Adventure", "Thriller"], "title": ["Mad Max Beyond Thunderdome"]},
{"url": ["http://www.imdb.com/title/tt3097204/"], "rating": [" 7.6 "], "year": ["2014"], "genre": ["Comedy"], "title": ["The Inbetweeners 2"]},
{"url": ["http://www.imdb.com/title/tt0462590/"], "rating": [" 6.5 "], "year": ["2006"], "genre": ["Crime", "Drama", "Music"], "title": ["Step Up"]},
{"url": ["http://www.imdb.com/title/tt2581244/"], "rating": [" 6.2 "], "year": ["2014"], "genre": ["Comedy", "Horror", "Romance"], "title": ["Life After Beth"]},
{"url": ["http://www.imdb.com/title/tt1939659/"], "rating": [" 6.0 "], "year": ["2013"], "genre": ["Drama", "Horror"], "title": ["Carrie"]},
{"url": ["http://www.imdb.com/title/tt1538403/"], "rating": [" 6.0 "], "year": ["2013"], "genre": ["Action", "Adventure", "Fantasy"], "title": ["The Mortal Instruments: City of Bones"]},
{"url": ["http://www.imdb.com/title/tt2312718/"], "rating": [" 6.5 "], "year": ["2013"], "genre": ["Action", "Crime", "Thriller"], "title": ["Homefront"]},
{"url": ["http://www.imdb.com/title/tt2872718/"], "rating": [], "year": ["2014"], "genre": ["Crime", "Drama"], "title": ["Nightcrawler"]},
{"url": ["http://www.imdb.com/title/tt0372784/"], "rating": [" 8.3 "], "year": ["2005"], "genre": ["Action", "Thriller"], "title": ["Batman Begins"]},
{"url": ["http://www.imdb.com/title/tt0948470/"], "rating": [" 7.1 "], "year": ["2012"], "genre": ["Action", "Adventure", "Fantasy"], "title": ["The Amazing Spider-Man"]},
{"url": ["http://www.imdb.com/title/tt1454468/"], "rating": [" 8.0 "], "year": ["2013"], "genre": ["Sci-Fi", "Thriller"], "title": ["Gravity"]},
{"url": ["http://www.imdb.com/title/tt1392214/"], "rating": [" 8.1 "], "year": ["2013"], "genre": ["Crime", "Drama", "Thriller"], "title": ["Prisoners"]},
{"url": ["http://www.imdb.com/title/tt1650554/"], "rating": [" 6.7 "], "year": ["2013"], "genre": ["Action", "Comedy", "Crime"], "title": ["Kick-Ass 2"]},
{"url": ["http://www.imdb.com/title/tt1748122/"], "rating": [" 7.8 "], "year": ["2012"], "genre": ["Comedy", "Drama", "Romance"], "title": ["Moonrise Kingdom"]},
{"url": ["http://www.imdb.com/title/tt2788710/"], "rating": [], "year": ["2014"], "genre": ["Comedy"], "title": ["The Interview"]},
{"url": ["http://www.imdb.com/title/tt1193138/"], "rating": [" 7.5 "], "year": ["2009"], "genre": ["Drama", "Romance"], "title": ["Up in the Air"]},
{"url": ["http://www.imdb.com/title/tt0266543/"], "rating": [" 8.2 "], "year": ["2003"], "genre": ["Animation", "Adventure", "Comedy"], "title": ["Finding Nemo"]},
{"url": ["http://www.imdb.com/title/tt0075314/"], "rating": [" 8.4 "], "year": ["1976"], "genre": ["Crime", "Drama"], "title": ["Taxi Driver"]},
{"url": ["http://www.imdb.com/title/tt1790809/"], "rating": [], "year": ["2017"], "genre": ["Action", "Adventure", "Comedy"], "title": ["Pirates of the Caribbean: Dead Men Tell No Tales"]},
{"url": ["http://www.imdb.com/title/tt0078788/"], "rating": [" 8.5 "], "year": ["1979"], "genre": ["Drama", "War"], "title": ["Apocalypse Now"]},
{"url": ["http://www.imdb.com/title/tt1499658/"], "rating": [" 6.9 "], "year": ["2011"], "genre": ["Comedy", "Crime"], "title": ["Horrible Bosses"]},
{"url": ["http://www.imdb.com/title/tt1464540/"], "rating": [" 6.1 "], "year": ["2011"], "genre": ["Action", "Adventure", "Sci-Fi"], "title": ["I Am Number Four"]},
{"url": ["http://www.imdb.com/title/tt3433074/"], "rating": [" 4.0 "], "year": ["2014"], "genre": ["Comedy"], "title": ["Mrs. Brown's Boys D'Movie"]},
{"url": ["http://www.imdb.com/title/tt0338013/"], "rating": [" 8.4 "], "year": ["2004"], "genre": ["Drama", "Romance", "Sci-Fi"], "title": ["Eternal Sunshine of the Spotless Mind"]},
{"url": ["http://www.imdb.com/title/tt1321870/"], "rating": [" 6.8 "], "year": ["2013"], "genre": ["Action", "Crime", "Drama"], "title": ["Gangster Squad"]},
{"url": ["http://www.imdb.com/title/tt2238050/"], "rating": [" 7.1 "], "year": ["2014"], "genre": ["Drama", "Thriller"], "title": ["White Bird in a Blizzard"]},
{"url": ["http://www.imdb.com/title/tt1560747/"], "rating": [" 7.1 "], "year": ["2012"], "genre": ["Drama"], "title": ["The Master"]},
{"url": ["http://www.imdb.com/title/tt0453556/"], "rating": [" 6.4 "], "year": ["2007"], "genre": ["Animation", "Action", "Adventure"], "title": ["TMNT"]},
{"url": ["http://www.imdb.com/title/tt2567712/"], "rating": [" 7.6 "], "year": ["2013"], "genre": ["Drama"], "title": ["Starred Up"]},
{"url": ["http://www.imdb.com/title/tt0800080/"], "rating": [" 6.9 "], "year": ["2008"], "genre": ["Action", "Sci-Fi", "Thriller"], "title": ["The Incredible Hulk"]},
{"url": ["http://www.imdb.com/title/tt2239832/"], "rating": [" 5.6 "], "year": ["2014"], "genre": ["Comedy"], "title": ["Think Like a Man Too"]},
{"url": ["http://www.imdb.com/title/tt0978764/"], "rating": [" 6.1 "], "year": ["2011"], "genre": ["Action", "Adventure", "Fantasy"], "title": ["Sucker Punch"]},
{"url": ["http://www.imdb.com/title/tt1606389/"], "rating": [" 6.8 "], "year": ["2012"], "genre": ["Drama", "Romance"], "title": ["The Vow"]},
{"url": ["http://www.imdb.com/title/tt1092026/"], "rating": [" 7.1 "], "year": ["2011"], "genre": ["Adventure", "Comedy", "Sci-Fi"], "title": ["Paul"]},
{"url": ["http://www.imdb.com/title/tt1772341/"], "rating": [" 7.8 "], "year": ["2012"], "genre": ["Animation", "Adventure", "Comedy"], "title": ["Wreck-It Ralph"]},
{"url": ["http://www.imdb.com/title/tt2334873/"], "rating": [" 7.4 "], "year": ["2013"], "genre": ["Comedy", "Drama"], "title": ["Blue Jasmine"]},
{"url": ["http://www.imdb.com/title/tt1386703/"], "rating": [" 6.3 "], "year": ["2012"], "genre": ["Action", "Adventure", "Mystery"], "title": ["Total Recall"]},
{"url": ["http://www.imdb.com/title/tt0245429/"], "rating": [" 8.6 "], "year": ["2001"], "genre": ["Animation", "Adventure", "Family"], "title": ["Spirited Away"]},
{"url": ["https://pro-labs.imdb.com/title/tt1790809?d=tt_indev"], "rating": [], "year": [], "genre": [], "title": []},
{"url": ["http://www.imdb.com/title/tt0147800/"], "rating": [" 7.2 "], "year": ["1999"], "genre": ["Comedy", "Drama", "Romance"], "title": ["10 Things I Hate About You"]},
{"url": ["http://www.imdb.com/title/tt0414387/"], "rating": [" 7.8 "], "year": ["2005"], "genre": ["Drama", "Romance"], "title": ["Pride & Prejudice"]},
{"url": ["http://www.imdb.com/title/tt3291150/"], "rating": [], "year": [], "genre": ["Action", "Adventure"], "title": ["The Expendables 4"]},
{"url": ["http://www.imdb.com/title/tt2106476/"], "rating": [" 8.3 "], "year": ["2012"], "genre": ["Drama"], "title": ["The Hunt"]},
{"url": ["http://www.imdb.com/title/tt0295297/"], "rating": [" 7.3 "], "year": ["2002"], "genre": ["Adventure", "Family", "Fantasy"], "title": ["Harry Potter and the Chamber of Secrets"]},
{"url": ["http://www.imdb.com/title/tt0398286/"], "rating": [" 7.9 "], "year": ["2010"], "genre": ["Animation", "Comedy", "Family"], "title": ["Tangled"]},
{"url": ["http://www.imdb.com/title/tt1311071/"], "rating": [" 6.5 "], "year": ["2013"], "genre": ["Biography", "Drama", "Romance"], "title": ["Kill Your Darlings"]},
{"url": ["http://www.imdb.com/title/tt1007028/"], "rating": [" 6.7 "], "year": ["2008"], "genre": ["Comedy", "Romance"], "title": ["Zack and Miri Make a Porno"]},
{"url": ["http://www.imdb.com/title/tt2884206/"], "rating": [" 7.2 "], "year": ["2014"], "genre": ["Drama", "Sci-Fi"], "title": ["I Origins"]},
{"url": ["http://www.imdb.com/title/tt0970452/"], "rating": [" 6.1 "], "year": ["2009"], "genre": ["Action", "Adventure", "Fantasy"], "title": ["Solomon Kane"]},
{"url": ["http://www.imdb.com/title/tt0240772/"], "rating": [" 7.8 "], "year": ["2001"], "genre": ["Crime", "Thriller"], "title": ["Ocean's Eleven"]},
{"url": ["http://www.imdb.com/title/tt0119116/"], "rating": [" 7.6 "], "year": ["1997"], "genre": ["Action", "Adventure", "Sci-Fi"], "title": ["The Fifth Element"]},
{"url": ["http://www.imdb.com/title/tt0493464/"], "rating": [" 6.7 "], "year": ["2008"], "genre": ["Action", "Crime", "Fantasy"], "title": ["Wanted"]},
{"url": ["http://www.imdb.com/title/tt0108037/"], "rating": [" 7.8 "], "year": ["1993"], "genre": ["Comedy", "Drama", "Family"], "title": ["The Sandlot"]},
{"url": ["http://www.imdb.com/title/tt0803096/"], "rating": [], "year": ["2016"], "genre": ["Action", "Adventure", "Fantasy"], "title": ["Warcraft"]},
{"url": ["http://www.imdb.com/title/tt1815862/"], "rating": [" 5.0 "], "year": ["2013"], "genre": ["Action", "Adventure", "Sci-Fi"], "title": ["After Earth"]},
{"url": ["http://www.imdb.com/title/tt1049413/"], "rating": [" 8.3 "], "year": ["2009"], "genre": ["Animation", "Adventure", "Drama"], "title": ["Up"]},
{"url": ["http://www.imdb.com/title/tt0103064/"], "rating": [" 8.5 "], "year": ["1991"], "genre": ["Action", "Sci-Fi", "Thriller"], "title": ["Terminator 2: Judgment Day"]},
{"url": ["http://www.imdb.com/title/tt2467046/"], "rating": [], "year": ["2014"], "genre": ["Action", "Sci-Fi", "Thriller"], "title": ["Left Behind"]},
{"url": ["http://www.imdb.com/title/tt1512235/"], "rating": [" 6.8 "], "year": ["2010"], "genre": ["Comedy", "Drama"], "title": ["Super"]},
{"url": ["https://pro-labs.imdb.com/title/tt3291150?d=tt_indev"], "rating": [], "year": [], "genre": [], "title": []},
{"url": ["http://www.imdb.com/title/tt0276751/"], "rating": [" 7.1 "], "year": ["2002"], "genre": ["Comedy", "Drama", "Romance"], "title": ["About a Boy"]},
{"url": ["http://www.imdb.com/title/tt0486655/"], "rating": [" 7.8 "], "year": ["2007"], "genre": ["Adventure", "Family", "Fantasy"], "title": ["Stardust"]},
{"url": ["http://www.imdb.com/title/tt0338526/"], "rating": [" 5.9 "], "year": ["2004"], "genre": ["Action", "Adventure", "Fantasy"], "title": ["Van Helsing"]},
{"url": ["http://www.imdb.com/title/tt0268978/"], "rating": [" 8.2 "], "year": ["2001"], "genre": ["Biography", "Drama"], "title": ["A Beautiful Mind"]},
{"url": ["http://www.imdb.com/title/tt0467406/"], "rating": [" 7.6 "], "year": ["2007"], "genre": ["Comedy", "Drama", "Romance"], "title": ["Juno"]},
{"url": ["http://www.imdb.com/title/tt1702439/"], "rating": [" 6.7 "], "year": ["2013"], "genre": ["Drama", "Romance", "Thriller"], "title": ["Safe Haven"]},
{"url": ["http://www.imdb.com/title/tt0087332/"], "rating": [" 7.8 "], "year": ["1984"], "genre": ["Comedy", "Fantasy", "Sci-Fi"], "title": ["Ghostbusters"]},
{"url": ["http://www.imdb.com/title/tt1855199/"], "rating": [" 7.7 "], "year": ["2012"], "genre": ["Crime", "Drama", "Thriller"], "title": ["End of Watch"]},
{"url": ["http://www.imdb.com/title/tt1126591/"], "rating": [" 6.3 "], "year": ["2010"], "genre": ["Drama", "Musical", "Romance"], "title": ["Burlesque"]},
{"url": ["http://www.imdb.com/title/tt0758746/"], "rating": [" 5.6 "], "year": ["2009"], "genre": ["Horror"], "title": ["Friday the 13th"]},
{"url": ["http://www.imdb.com/title/tt0181875/"], "rating": [" 8.0 "], "year": ["2000"], "genre": ["Drama", "Music", "Romance"], "title": ["Almost Famous"]},
{"url": ["http://www.imdb.com/title/tt1453405/"], "rating": [" 7.4 "], "year": ["2013"], "genre": ["Animation", "Adventure", "Comedy"], "title": ["Monsters University"]},
{"url": ["http://www.imdb.com/title/tt1294226/"], "rating": [" 5.7 "], "year": ["2010"], "genre": ["Drama", "Romance"], "title": ["The Last Song"]},
{"url": ["http://www.imdb.com/title/tt0088323/"], "rating": [" 7.4 "], "year": ["1984"], "genre": ["Adventure", "Drama", "Family"], "title": ["The NeverEnding Story"]},
{"url": ["http://www.imdb.com/title/tt0212985/"], "rating": [" 6.7 "], "year": ["2001"], "genre": ["Crime", "Drama", "Thriller"], "title": ["Hannibal"]},
{"url": ["http://www.imdb.com/title/tt0388795/"], "rating": [" 7.7 "], "year": ["2005"], "genre": ["Drama", "Romance"], "title": ["Brokeback Mountain"]},
{"url": ["http://www.imdb.com/title/tt0363547/"], "rating": [" 7.4 "], "year": ["2004"], "genre": ["Action", "Horror", "Sci-Fi"], "title": ["Dawn of the Dead"]},
{"url": ["http://www.imdb.com/title/tt1763303/"], "rating": [" 7.0 "], "year": ["2012"], "genre": ["Comedy", "Drama", "Romance"], "title": ["The First Time"]},
{"url": ["http://www.imdb.com/title/tt0465494/"], "rating": [" 6.3 "], "year": ["2007"], "genre": ["Action", "Crime", "Drama"], "title": ["Hitman"]},
{"url": ["http://www.imdb.com/title/tt2573858/"], "rating": [" 6.1 "], "year": ["2013"], "genre": ["Comedy"], "title": ["The Bachelor Weekend"]},
{"url": ["http://www.imdb.com/title/tt1228987/"], "rating": [" 7.2 "], "year": ["2010"], "genre": ["Drama", "Horror", "Mystery"], "title": ["Let Me In"]},
{"url": ["http://www.imdb.com/title/tt0348150/"], "rating": [" 6.2 "], "year": ["2006"], "genre": ["Action", "Adventure", "Fantasy"], "title": ["Superman Returns"]},
{"url": ["http://www.imdb.com/title/tt1591095/"], "rating": [" 6.8 "], "year": ["2010"], "genre": ["Horror", "Thriller"], "title": ["Insidious"]},
{"url": ["http://www.imdb.com/title/tt0087800/"], "rating": [" 7.5 "], "year": ["1984"], "genre": ["Horror"], "title": ["A Nightmare on Elm Street"]},
{"url": ["http://www.imdb.com/title/tt1630029/"], "rating": [], "year": ["2016"], "genre": ["Action", "Adventure", "Fantasy"], "title": ["Avatar 2"]},
{"url": ["http://www.imdb.com/title/tt0232500/"], "rating": [" 6.6 "], "year": ["2001"], "genre": ["Action", "Crime", "Thriller"], "title": ["The Fast and the Furious"]},
{"url": ["http://www.imdb.com/title/tt2345737/"], "rating": [" 7.3 "], "year": ["2014"], "genre": ["Crime", "Drama"], "title": ["The Rover"]},
{"url": ["http://www.imdb.com/title/tt0330793/"], "rating": [" 6.4 "], "year": ["2004"], "genre": ["Action", "Crime", "Drama"], "title": ["The Punisher"]},
{"url": ["http://www.imdb.com/title/tt0472043/"], "rating": [" 7.8 "], "year": ["2006"], "genre": ["Action", "Adventure", "Drama"], "title": ["Apocalypto"]},
{"url": ["http://www.imdb.com/title/tt1284575/"], "rating": [" 5.7 "], "year": ["2011"], "genre": ["Comedy"], "title": ["Bad Teacher"]},
{"url": ["http://www.imdb.com/title/tt0097757/"], "rating": [" 7.6 "], "year": ["1989"], "genre": ["Animation", "Family", "Fantasy"], "title": ["The Little Mermaid"]},
{"url": ["http://www.imdb.com/title/tt2398249/"], "rating": [" 5.7 "], "year": ["2014"], "genre": ["Comedy"], "title": ["They Came Together"]},
{"url": ["http://www.imdb.com/title/tt1136608/"], "rating": [" 8.0 "], "year": ["2009"], "genre": ["Action", "Sci-Fi", "Thriller"], "title": ["District 9"]},
{"url": ["http://www.imdb.com/title/tt0478311/"], "rating": [" 7.1 "], "year": ["2007"], "genre": ["Comedy", "Drama", "Romance"], "title": ["Knocked Up"]},
{"url": ["http://www.imdb.com/title/tt0092890/"], "rating": [" 6.8 "], "year": ["1987"], "genre": ["Drama", "Music", "Romance"], "title": ["Dirty Dancing"]},
{"url": ["http://www.imdb.com/title/tt1821549/"], "rating": [" 7.8 "], "year": ["2013"], "genre": ["Adventure", "Drama"], "title": ["Nebraska"]},
{"url": ["http://www.imdb.com/title/tt0114436/"], "rating": [" 4.5 "], "year": ["1995"], "genre": ["Drama"], "title": ["Showgirls"]},
{"url": ["http://www.imdb.com/title/tt0032138/"], "rating": [" 8.1 "], "year": ["1939"], "genre": ["Adventure", "Family", "Fantasy"], "title": ["The Wizard of Oz"]},
{"url": ["http://www.imdb.com/title/tt2756032/"], "rating": [" 7.4 "], "year": ["2014"], "genre": ["Comedy", "Drama", "Romance"], "title": ["The One I Love"]},
{"url": ["http://www.imdb.com/title/tt0373883/"], "rating": [" 6.1 "], "year": ["2007"], "genre": ["Horror"], "title": ["Halloween"]},
{"url": ["http://www.imdb.com/title/tt2402085/"], "rating": [" 5.5 "], "year": ["2013"], "genre": ["Biography", "Drama", "Music"], "title": ["Jimi: All Is by My Side"]},
{"url": ["http://www.imdb.com/title/tt1682180/"], "rating": [" 6.9 "], "year": ["2013"], "genre": ["Drama", "Mystery", "Thriller"], "title": ["Stoker"]},
{"url": ["http://www.imdb.com/title/tt1211837/"], "rating": [], "year": ["2016"], "genre": ["Adventure", "Fantasy"], "title": ["Doctor Strange"]},
{"url": ["http://www.imdb.com/title/tt2132285/"], "rating": [" 5.6 "], "year": ["2013"], "genre": ["Biography", "Crime", "Drama"], "title": ["The Bling Ring"]},
{"url": ["http://www.imdb.com/title/tt1650062/"], "rating": [" 7.1 "], "year": ["2011"], "genre": ["Mystery", "Sci-Fi", "Thriller"], "title": ["Super 8"]},
{"url": ["http://www.imdb.com/title/tt2401807/"], "rating": [" 5.0 "], "year": ["2014"], "genre": ["Action", "Crime", "Thriller"], "title": ["Rage"]},
{"url": ["http://www.imdb.com/title/tt1217209/"], "rating": [" 7.2 "], "year": ["2012"], "genre": ["Animation", "Adventure", "Comedy"], "title": ["Brave"]},
{"url": ["http://www.imdb.com/title/tt1596343/"], "rating": [" 7.3 "], "year": ["2011"], "genre": ["Action", "Crime", "Thriller"], "title": ["Fast Five"]},
{"url": ["http://www.imdb.com/title/tt0425112/"], "rating": [" 7.9 "], "year": ["2007"], "genre": ["Comedy"], "title": ["Hot Fuzz"]},
{"url": ["http://www.imdb.com/title/tt1375670/"], "rating": [" 5.9 "], "year": ["2010"], "genre": ["Comedy"], "title": ["Grown Ups"]},
{"url": ["http://www.imdb.com/title/tt0071853/"], "rating": [" 8.4 "], "year": ["1975"], "genre": ["Adventure", "Comedy", "Fantasy"], "title": ["Monty Python and the Holy Grail"]},
{"url": ["http://www.imdb.com/title/tt1232200/"], "rating": [" 5.6 "], "year": ["2012"], "genre": ["Comedy"], "title": ["That's My Boy"]},
{"url": ["http://www.imdb.com/title/tt3063516/"], "rating": [" 6.6 "], "year": ["2013"], "genre": ["Comedy"], "title": ["Jackass Presents: Bad Grandpa"]},
{"url": ["http://www.imdb.com/title/tt2667918/"], "rating": [" 5.7 "], "year": ["2014"], "genre": ["Drama"], "title": ["About Alex"]},
{"url": ["http://www.imdb.com/title/tt0080339/"], "rating": [" 7.8 "], "year": ["1980"], "genre": ["Comedy"], "title": ["Airplane!"]},
{"url": ["http://www.imdb.com/title/tt0365907/"], "rating": [], "year": ["2014"], "genre": ["Action", "Crime", "Mystery"], "title": ["A Walk Among the Tombstones"]},
{"url": ["http://www.imdb.com/title/tt0017136/"], "rating": [" 8.4 "], "year": ["1927"], "genre": ["Drama", "Sci-Fi"], "title": ["Metropolis"]},
{"url": ["http://www.imdb.com/title/tt1893256/"], "rating": [" 6.2 "], "year": ["2013"], "genre": ["Action", "Crime", "Drama"], "title": ["Redemption"]},
{"url": ["http://www.imdb.com/title/tt1121096/"], "rating": [], "year": ["2015"], "genre": ["Adventure", "Family", "Fantasy"], "title": ["Seventh Son"]},
{"url": ["http://www.imdb.com/title/tt1853739/"], "rating": [" 6.5 "], "year": ["2011"], "genre": ["Horror", "Thriller"], "title": ["You're Next"]},
{"url": ["http://www.imdb.com/title/tt0783233/"], "rating": [" 7.8 "], "year": ["2007"], "genre": ["Drama", "Mystery", "Romance"], "title": ["Atonement"]},
{"url": ["http://www.imdb.com/title/tt0398165/"], "rating": [" 6.3 "], "year": ["2005"], "genre": ["Comedy", "Crime", "Sport"], "title": ["The Longest Yard"]},
{"url": ["http://www.imdb.com/title/tt1038686/"], "rating": [" 5.1 "], "year": ["2010"], "genre": ["Action", "Fantasy", "Horror"], "title": ["Legion"]},
{"url": ["http://www.imdb.com/title/tt1872194/"], "rating": [], "year": ["2014"], "genre": ["Drama"], "title": ["The Judge"]},
{"url": ["http://www.imdb.com/title/tt0129387/"], "rating": [" 7.1 "], "year": ["1998"], "genre": ["Comedy", "Romance"], "title": ["There's Something About Mary"]},
{"url": ["https://pro-labs.imdb.com/title/tt1211837?d=tt_indev"], "rating": [], "year": [], "genre": [], "title": []},
{"url": ["http://www.imdb.com/title/tt1781769/"], "rating": [" 6.6 "], "year": ["2012"], "genre": ["Drama"], "title": ["Anna Karenina"]},
{"url": ["http://www.imdb.com/title/tt2205401/"], "rating": [], "year": ["2014"], "genre": ["Drama", "Thriller"], "title": ["Addicted"]},
{"url": ["http://www.imdb.com/title/tt2343793/"], "rating": [" 6.5 "], "year": ["2013"], "genre": ["Drama", "Romance"], "title": ["Third Person"]},
{"url": ["http://www.imdb.com/title/tt1041829/"], "rating": [" 6.7 "], "year": ["2009"], "genre": ["Comedy", "Drama", "Romance"], "title": ["The Proposal"]},
{"url": ["http://www.imdb.com/title/tt2009606/"], "rating": [" 5.4 "], "year": ["2013"], "genre": ["Drama"], "title": ["Believe"]},
{"url": ["http://www.imdb.com/title/tt1967545/"], "rating": [" 6.9 "], "year": ["2013"], "genre": ["Drama"], "title": ["Labor Day"]},
{"url": ["http://www.imdb.com/title/tt0816462/"], "rating": [" 5.2 "], "year": ["2011"], "genre": ["Action", "Adventure", "Fantasy"], "title": ["Conan the Barbarian"]},
{"url": ["http://www.imdb.com/title/tt1189340/"], "rating": [" 7.3 "], "year": ["2011"], "genre": ["Crime", "Drama", "Thriller"], "title": ["The Lincoln Lawyer"]},
{"url": ["http://www.imdb.com/title/tt1663202/"], "rating": [], "year": ["2015"], "genre": ["Adventure", "Drama"], "title": ["The Revenant"]},
{"url": ["http://www.imdb.com/title/tt0080684/"], "rating": [" 8.8 "], "year": ["1980"], "genre": ["Action", "Adventure", "Fantasy"], "title": ["Star Wars: Episode V - The Empire Strikes Back"]},
{"url": ["http://www.imdb.com/title/tt1924396/"], "rating": [" 7.9 "], "year": ["2013"], "genre": ["Crime", "Drama", "Mystery"], "title": ["The Best Offer"]},
{"url": ["http://www.imdb.com/title/tt0800320/"], "rating": [" 5.8 "], "year": ["2010"], "genre": ["Action", "Adventure", "Fantasy"], "title": ["Clash of the Titans"]},
{"url": ["http://www.imdb.com/title/tt0086190/"], "rating": [" 8.4 "], "year": ["1983"], "genre": ["Action", "Adventure", "Fantasy"], "title": ["Star Wars: Episode VI - Return of the Jedi"]},
{"url": ["http://www.imdb.com/title/tt2848310/"], "rating": [], "year": [], "genre": ["Action", "Adventure", "Drama"], "title": ["The Mortal Instruments: City of Ashes"]},
{"url": ["http://www.imdb.com/title/tt0320661/"], "rating": [" 7.2 "], "year": ["2005"], "genre": ["Action", "Adventure", "Drama"], "title": ["Kingdom of Heaven"]},
{"url": ["http://www.imdb.com/title/tt0758752/"], "rating": [" 6.7 "], "year": ["2010"], "genre": ["Comedy", "Drama", "Romance"], "title": ["Love & Other Drugs"]},
{"url": ["http://www.imdb.com/title/tt2017038/"], "rating": [" 6.9 "], "year": ["2013"], "genre": ["Action", "Adventure", "Drama"], "title": ["All Is Lost"]},
{"url": ["http://www.imdb.com/title/tt2390237/"], "rating": [" 6.2 "], "year": ["2014"], "genre": ["Comedy"], "title": ["Cuban Fury"]},
{"url": ["http://www.imdb.com/title/tt1324999/"], "rating": [" 4.8 "], "year": ["2011"], "genre": ["Adventure", "Drama", "Fantasy"], "title": ["The Twilight Saga: Breaking Dawn - Part 1"]},
{"url": ["http://www.imdb.com/title/tt0080678/"], "rating": [" 8.3 "], "year": ["1980"], "genre": ["Biography", "Drama"], "title": ["The Elephant Man"]},
{"url": ["http://www.imdb.com/title/tt0485947/"], "rating": [" 7.9 "], "year": ["2009"], "genre": ["Drama", "Fantasy", "Romance"], "title": ["Mr. Nobody"]},
{"url": ["http://www.imdb.com/title/tt0167404/"], "rating": [" 8.2 "], "year": ["1999"], "genre": ["Drama", "Mystery", "Thriller"], "title": ["The Sixth Sense"]},
{"url": ["http://www.imdb.com/title/tt2126355/"], "rating": [], "year": ["2015"], "genre": ["Action", "Drama", "Thriller"], "title": ["San Andreas"]},
{"url": ["http://www.imdb.com/title/tt2263814/"], "rating": [" 4.9 "], "year": ["2013"], "genre": ["Thriller"], "title": ["The Maid's Room"]},
{"url": ["http://www.imdb.com/title/tt0435761/"], "rating": [" 8.4 "], "year": ["2010"], "genre": ["Animation", "Adventure", "Comedy"], "title": ["Toy Story 3"]},
{"url": ["http://www.imdb.com/title/tt1747958/"], "rating": [" 6.5 "], "year": ["2013"], "genre": ["Crime", "Drama", "Thriller"], "title": ["Blood Ties"]},
{"url": ["http://www.imdb.com/title/tt2317225/"], "rating": [" 6.1 "], "year": ["2013"], "genre": ["Sci-Fi", "Thriller"], "title": ["The Machine"]},
{"url": ["http://www.imdb.com/title/tt1951261/"], "rating": [" 5.9 "], "year": ["2013"], "genre": ["Comedy"], "title": ["The Hangover Part III"]},
{"url": ["http://www.imdb.com/title/tt2053463/"], "rating": [" 7.1 "], "year": ["2013"], "genre": ["Crime", "Drama", "Thriller"], "title": ["Side Effects"]},
{"url": ["http://www.imdb.com/title/tt0389860/"], "rating": [" 6.5 "], "year": ["2006"], "genre": ["Comedy", "Drama", "Fantasy"], "title": ["Click"]},
{"url": ["http://www.imdb.com/title/tt1605717/"], "rating": [" 7.4 "], "year": ["2014"], "genre": ["Comedy", "Drama", "Mystery"], "title": ["Frank"]},
{"url": ["http://www.imdb.com/title/tt1767354/"], "rating": [" 6.8 "], "year": ["2013"], "genre": ["Fantasy", "Mystery", "Thriller"], "title": ["Odd Thomas"]},
{"url": ["http://www.imdb.com/title/tt0117998/"], "rating": [" 6.2 "], "year": ["1996"], "genre": ["Action", "Adventure", "Drama"], "title": ["Twister"]},
{"url": ["http://www.imdb.com/title/tt0361862/"], "rating": [" 7.8 "], "year": ["2004"], "genre": ["Drama", "Thriller"], "title": ["The Machinist"]},
{"url": ["http://www.imdb.com/title/tt1272878/"], "rating": [" 6.8 "], "year": ["2013"], "genre": ["Action", "Comedy", "Crime"], "title": ["2 Guns"]},
{"url": ["https://pro-labs.imdb.com/title/tt2848310?d=tt_indev"], "rating": [], "year": [], "genre": [], "title": []},
{"url": ["http://www.imdb.com/title/tt1436562/"], "rating": [" 7.0 "], "year": ["2011"], "genre": ["Animation", "Adventure", "Comedy"], "title": ["Rio"]},
{"url": ["http://www.imdb.com/title/tt3152098/"], "rating": [" 2.9 "], "year": ["2014"], "genre": ["Action", "Sci-Fi", "Thriller"], "title": ["Mega Shark vs. Mecha Shark"]},
{"url": ["http://www.imdb.com/title/tt0102057/"], "rating": [" 6.6 "], "year": ["1991"], "genre": ["Adventure", "Comedy", "Family"], "title": ["Hook"]},
{"url": ["http://www.imdb.com/title/tt0443706/"], "rating": [" 7.7 "], "year": ["2007"], "genre": ["Crime", "Drama", "Mystery"], "title": ["Zodiac"]},
{"url": ["http://www.imdb.com/title/tt1951266/"], "rating": [], "year": ["2015"], "genre": ["Adventure", "Sci-Fi"], "title": ["The Hunger Games: Mockingjay - Part 2"]},
{"url": ["http://www.imdb.com/title/tt1078940/"], "rating": [" 5.5 "], "year": ["2009"], "genre": ["Comedy"], "title": ["Couples Retreat"]},
{"url": ["http://www.imdb.com/title/tt0910936/"], "rating": [" 7.0 "], "year": ["2008"], "genre": ["Action", "Comedy", "Crime"], "title": ["Pineapple Express"]},
{"url": ["http://www.imdb.com/title/tt0062622/"], "rating": [" 8.3 "], "year": ["1968"], "genre": ["Adventure", "Mystery", "Sci-Fi"], "title": ["2001: A Space Odyssey"]},
{"url": ["http://www.imdb.com/title/tt1985966/"], "rating": [" 6.5 "], "year": ["2013"], "genre": ["Animation", "Comedy", "Family"], "title": ["Cloudy with a Chance of Meatballs 2"]},
{"url": ["http://www.imdb.com/title/tt0050083/"], "rating": [" 8.9 "], "year": ["1957"], "genre": ["Drama"], "title": ["12 Angry Men"]},
{"url": ["http://www.imdb.com/title/tt2034031/"], "rating": [" 8.1 "], "year": ["2014"], "genre": ["Comedy", "Romance"], "title": ["Laggies"]},
{"url": ["http://www.imdb.com/title/tt0386588/"], "rating": [" 6.7 "], "year": ["2005"], "genre": ["Comedy", "Romance"], "title": ["Hitch"]},
{"url": ["http://www.imdb.com/title/tt0458352/"], "rating": [" 6.8 "], "year": ["2006"], "genre": ["Comedy", "Drama", "Romance"], "title": ["The Devil Wears Prada"]},
{"url": ["http://www.imdb.com/title/tt1907668/"], "rating": [" 7.3 "], "year": ["2012"], "genre": ["Drama", "Thriller"], "title": ["Flight"]},
{"url": ["http://www.imdb.com/title/tt1496025/"], "rating": [" 6.4 "], "year": ["2012"], "genre": ["Action", "Fantasy", "Horror"], "title": ["Underworld: Awakening"]},
{"url": ["http://www.imdb.com/title/tt0290334/"], "rating": [" 7.5 "], "year": ["2003"], "genre": ["Action", "Adventure", "Sci-Fi"], "title": ["X-Men 2"]},
{"url": ["http://www.imdb.com/title/tt0417741/"], "rating": [" 7.5 "], "year": ["2009"], "genre": ["Adventure", "Family", "Fantasy"], "title": ["Harry Potter and the Half-Blood Prince"]},
{"url": ["http://www.imdb.com/title/tt0878804/"], "rating": [" 7.7 "], "year": ["2009"], "genre": ["Biography", "Drama", "Sport"], "title": ["The Blind Side"]},
{"url": ["http://www.imdb.com/title/tt2209418/"], "rating": [" 8.0 "], "year": ["2013"], "genre": ["Drama", "Romance"], "title": ["Before Midnight"]},
{"url": ["http://www.imdb.com/title/tt2083355/"], "rating": [" 6.7 "], "year": ["2013"], "genre": ["Comedy", "Drama"], "title": ["The Best Man Holiday"]},
{"url": ["http://www.imdb.com/title/tt3148834/"], "rating": [" 6.5 "], "year": ["2013"], "genre": ["Animation", "Adventure", "Family"], "title": ["The House of Magic"]},
{"url": ["http://www.imdb.com/title/tt0119282/"], "rating": [" 7.2 "], "year": ["1997"], "genre": ["Animation", "Adventure", "Comedy"], "title": ["Hercules"]},
{"url": ["http://www.imdb.com/title/tt0093870/"], "rating": [" 7.5 "], "year": ["1987"], "genre": ["Action", "Crime", "Sci-Fi"], "title": ["RoboCop"]},
{"url": ["http://www.imdb.com/title/tt0265086/"], "rating": [" 7.7 "], "year": ["2001"], "genre": ["Drama", "History", "Thriller"], "title": ["Black Hawk Down"]}]


for i in range(0, 349):



print movie_list[1]['url'][0]



